package config

const (
	DB_PASSWORD = "DB_PASSWORD"
	DB_IP       = "DB_IP"
	DB_PORT     = "DB_PORT"
	DB_SSL_MODE = "DB_SSL_MODE"
	DB_URL      = "DB_URL"
	RPC_URL     = "RPC_URL"

	DB_EMBED_PORT         = "DB_EMBED_PORT"
	DB_EMBED_USERNAME     = "DB_EMBED_USERNAME"
	DB_EMBED_PASSWORD     = "DB_EMBED_PASSWORD"
	DB_EMBED_DATABASE     = "DB_EMBED_DATABASE"
	DB_EMBED_SSL_MODE     = "DB_EMBED_SSL_MODE"
	DB_EMBED_RUNTIME_PATH = "DB_EMBED_RUNTIME_PATH"
)
